### ISSUE TITLE
it is found that when the number of user groups is greater than 2, the content of the configmap user-groups-map or user-gids-map does not match the actual one.

### ISSUE THREAD

**Issue by 18707602767** [OSC/k8-ldap-configmap#20]
**Environment:**
- Linux: CentOS Linux release 7.8.2003 (Core)
- kubernetes: V1.24.2
- CRI: Containerd
- LDAP: FreeIPA

**What happened:**
The k8-ldap-configmap char is installed in the k8s cluster, and it is found that when the number of user's groups is greater than 2, the content of the configmap user-groups-map or user-gids-map does not match the actual one.

**values.yaml file**
```
# Default values for k8-ldap-configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ldapUrl: 'ldap://10.49.118.102:389'
ldapTLS: false
ldapTLSVerify: true
ldapTLSCACert: ''
ldapGroupBaseDN: 'cn=groups,cn=accounts,dc=pl,dc=hpc'
ldapUserBaseDN: 'cn=users,cn=accounts,dc=pl,dc=hpc'
ldapBindDN: 'uid=rancher,cn=sysaccounts,cn=etc,dc=pl,dc=hpc'
ldapBindPassword: '1qavfsdfa'
ldapGroupFilter: '(objectClass=posixGroup)'
ldapUserFilter: '(objectClass=posixAccount)'
ldapMemberScheme: 'member'
ldapUserAttrMap: 'name=uid,uid=uidNumber,gid=gidNumber'
ldapGroupAttrMap: 'name=cn,gid=gidNumber'
mappers:
  - user-uid
  - user-gid
  - user-gids
  - user-groups
mappersUserFilter: []
mappersGroupFilter: []
userPrefix: ''
interval: 5s
# Set namespace of generated ConfigMaps
# Defaults to namespace of Chart release
namespaceConfigMap: "default"

extraArgs: []

image:
  repository: docker.io/ohiosupercomputer/k8-ldap-configmap
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride:
fullnameOverride:
namespace:

rbac:
  create: true
  serviceAccount:
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534

service:
  # Specifies whether a service should be created
  create: true
  type: ClusterIP
  port: 8080
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /metrics

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}

```
**kubectl get configmap user-groups-map -o yaml**
```
apiVersion: v1
data:
  admin: '["admins"]'
  zhanrd: '["test-1","test-3"]'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-01-09T09:08:41Z"
  name: user-groups-map
  namespace: default
  resourceVersion: "9170354"
  uid: 6fdb1e61-bd34-4cae-a886-a31864686d18

```
**id zhanrd**
```
uid=20000(zhanrd) gid=10000(test-1) groups=10000(test-1),10003(test-3),10002(test-2)
```
